remove QP's dependency on config
ease-lab/zipline pull request #5
Opened 2021-07-06 07:01 UTC by shyamjesal

- Replace config file with environment variables
  - split env variables in 2 files: network and xdt 
  - Added struct tags in `utils/common.go` for default config params.
  - `utils/common.go` now parses environment variables using [envconfig](github.com/kelseyhightower/envconfig) instead of config file
  - Added environment variables in Makefile
  - Created `user-functions/gx/gx.yaml` and `user-functions/fx/fx.yaml` for knative deployment

- Removed redundent`ChunkSize` in `proto/crossXDT` `proto/downXDT`
- Manually append headers in http proxy as extracting metadata from `r.Context()` does not work
- Removed Payload un-marshalling at `sdk/golang/destination.go` as the metadata is send using http headers.
- Removed global config variable in `utils/common.go`
  - removed global config and handler variables in `sdk/golang/destination.go`
- Changed default routing mode to "CutThrough" 
- changed h2c ports to 50051 in fx.yaml and gx.yaml

2021-07-06 16:28 UTC, ustiugov requested changes
need to be re-done using env variables instead of headers. btw, you may want to keep you LoadConfig function but in the knative mode, it should parse the env variables. **Do not parse them in many places in the code.**

2021-07-07 15:57 UTC, ustiugov requested changes
- [x] use underscores for env variables for readability
- [x] why routing is still a runtime argument? it should be via env vars
- [x] in the knative setup, hostnames and ports should not be configurable, they should have the default values. please remove redundant parameters
- [x] remove the global LoadConfig variable

2021-07-07 15:57 UTC, ustiugov commented on .github/workflows/xdt_tests.yml
> +          CHUNKSIZEINBYTES: 65536
it's not readable, please use underscores to separate words

2021-07-07 15:57 UTC, ustiugov commented on user-functions/.env
> +CHUNKSIZEINBYTES=65536
what is this file? why don't makefiles use it?

2021-07-07 15:57 UTC, ustiugov commented on user-functions/fx/fx.yaml
> +            - name: CHUNKSIZEINBYTES
in the knative setup, hostnames and ports should not be configurable, they should have the default values.

please clear the redundant parameters

2021-07-07 15:57 UTC, ustiugov commented on utils/common.go
> +var LoadConfig = ReadConfig()
instead of a global variable, every component should call ReadConfig(). Globals are bad style

2021-07-07 16:06 UTC, shyamjesal commented on user-functions/.env
> +CHUNKSIZEINBYTES=65536
this file is for loading env variables for docker compose run

2021-07-07 18:52 UTC, ustiugov requested changes

2021-07-07 18:52 UTC, ustiugov commented on queue-proxy/sQP/sQP.go
> +			if headers["routing"][0] == utils.STORE_FORWARD {
this is what I don't get. why is routing in the header? it should be upon startup with an env variable, right?

2021-07-07 18:52 UTC, ustiugov commented on sdk/golang/destination.go
> +		log.Infof("DST: using %s routing", headers["routing"][0])
shouldn't be in headers

2021-07-07 18:52 UTC, ustiugov commented on sdk/python/source.py
> +        ('routing', config['Routing']),
shouldn't be here

2021-07-07 18:52 UTC, ustiugov commented on sdk/python/test.py
> +            ('routing', config['Routing']),
shouldn't be in a header

2021-07-07 18:52 UTC, ustiugov commented on tests/integration_test.go
> +					"routing":  r.Header.Get("routing"),
shouldn't be in a header

2021-07-07 18:52 UTC, ustiugov commented on user-functions/dQP/dQP.go
> +					"routing":  r.Header.Get("routing"),
shouldn't be in a header

2021-07-07 18:52 UTC, ustiugov commented on Makefile
> +.EXPORT_ALL_VARIABLES:
is it possible to import it from the .env file that you use for docker compose? 2 sets of vars is hard to maintain

2021-07-07 18:52 UTC, ustiugov commented on user-functions/fx/fx.yaml
> +              containerPort: 50010
please use the same 50051 port in knative in all functions

2021-07-07 18:52 UTC, ustiugov commented on user-functions/gx/gx.yaml
> +              containerPort: 50007
50051 please

2021-07-08 09:43 UTC, ustiugov approved these changes

2021-07-08 09:46 UTC, merged