Fix tcp dial overhead
ease-lab/zipline pull request #6
Opened 2021-07-06 12:37 UTC by shyamjesal

- removed TCP dial overhead b/w dQP and DST from critical path
- fix benchmark test artifact path
- - removed TCP dial overhead b/w sQP and SRC

2021-07-06 16:32 UTC, ustiugov requested changes
- [x] splint long lines into many, lots of super long function definitions. 100 characters should be MAX
- [x] get rid of the init-time parameters inside RPCs

2021-07-06 16:32 UTC, ustiugov commented on tests/integration_test.go
> +	if err := sdk.InvokeWithXDT(url, preparePayload(), config.SQPServerHostname+config.SQPServerPort, chunkSizeInBytes, config.Routing, config.RPCTimeoutDuration); err != nil {
a very long line

2021-07-06 16:32 UTC, ustiugov commented on sdk/golang/source.go
> +func InvokeWithXDT(URL string, xdtPayload utils.Payload, sQPAddr string, chunkSizeInBytes int, routing string, RPCTimeout int) error {
a very long line

2021-07-09 13:11 UTC, shyamjesal commented
Both the TCP dial overheads are removed. I think the sQP-Src overhead is still in the critical path. Can you think of a way to solve this? How about making the connection in a separate go-routine?

2021-07-09 13:29 UTC, ustiugov requested changes

2021-07-09 13:29 UTC, ustiugov commented on sdk/golang/source.go
I suggest a minor refactoring: define a type, called XDT client. Then InitXDT would become a part of NewXDTClient call and Invoke(WithXDT postfix can be omitted) as well as PushData become the methods of that type. 

This way you don't need to pass the client as an argument

2021-07-13 17:11 UTC, ustiugov approved these changes

2021-07-14 03:28 UTC, merged